### ISSUE TITLE
Extant issues from Discord

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/FAMDB#1]
- [x] Missions with no files can't be marked as broken because you can't comment (#6)
- [x] GM missions need a separate ready state, so they can be marked ready without transferring to main (#7)
- [x] The playcount filter does not work
- [x] Mission names with commas break the session runlist feature (#8)
- [x] FAMDB is not HTTPS enabled
- [x] Using apostropes `'` in comments doesn't work properly
- [x] Creating a mission with a player count above 255 silently eats the mission, creating a new mission ID but not a listing, with no feedback to the user
- [x] It seems like comments can end up being displayed out of order
- [x] Add a searchable tag system, and possibly make descriptions searchable (#9)

The Sefrou-Ramal map has been added to the code here but requires deployment to the live version.

**Comment by SamLex** [comment]
> FAMDB is not HTTPS enabled

This was a server wide thing, which has now been enabled by @blip2. But this is causing the font not to load due to mixed content security policies. So I'll add an additional issue:

- [x] Change font to load over HTTPS
https://github.com/folkarps/FAMDB/blob/ce49ffa2e503372fef5d386ea846a6c6f6732a23/static/index.html#L12

ETA: I hot-patched this in the live version by changing the URL to 'https'

ETA2: Same issue in sessions.html (also hot-patched on live) - https://github.com/folkarps/FAMDB/blob/ce49ffa2e503372fef5d386ea846a6c6f6732a23/static/sessions.html#L11

ETA3: And a number of other pages as well (all hot-patched)

**Comment by SamLex** [comment]
The Sefrou-Ramal map change is now live, and the master branch is fully synced up with the live version. Now I'll start work on fixing these issues

**Comment by SamLex** [comment]
PlayCount filter fixed in #3; live site is updated

**Comment by SamLex** [comment]
> Creating a mission with a player count above 255 silently eats the mission, creating a new mission ID but not a listing, with no feedback to the user

I think this might be a display issue rather than the mission getting eaten. The "Slots" filter defaults to max 255; changing it to 999 max I can see a few missions with 999 slots listed.

@NikkoJT Can you try changing the slots max and see if those are your "eaten" missions? If so, I'll just change the filter to default to 999 max.

**Comment by SamLex** [comment]
>  It seems like comments can end up being displayed out of order

@NikkoJT Do you have a mission or two as examples of this?

**Comment by NikkoJT** [comment]
> Can you try changing the slots max and see if those are your "eaten" missions?

Yes, that's them. (I'm going to delete them now since they're redundant)

> Do you have a mission or two as examples of this?

I'm semi-confident that I did at the time of writing, but I no longer recall which. It's possible these were super-old comments from before they were attached to versions or something like that.

**Comment by SamLex** [comment]
RE: slots

Okay, I'll change the default max to 999, same as for playcount.

RE: comments

I think comments have always been attached to a version but have some complex rules about sorting them so might've been a non-obvious case of valid but weird sorting. I'll keep looking into it but let me know if you see another
Comment sorting rules:
https://github.com/folkarps/FAMDB/blob/ee6ac9ba95bf0e5e8afd7af17fb9c95b185b72c8/handlers/missions.py#L150-L173

**Comment by SamLex** [comment]
> Using apostropes ' in comments doesn't work properly

Fixed in #5. Same fix also means '<', '>', '&', and '"' (double-quote) should be shown properly in comments.

> Creating a mission with a player count above 255 silently eats the mission, creating a new mission ID but not a listing, with no feedback to the user

Fixed in #4 by raising the max Slots filter to 999 by default.



Both deployed on live server.

**Comment by SamLex** [comment]
I've split out the rest of the issues so they have their own dedicated spaces for discussion.

I'm going to "park" the comment order issues until I can find some examples.

**Comment by NikkoJT** [comment]
@SamLex Comment order issue detected!
Mission: Lost Sector: Frini North
Procedure: 
Mission had files with comments up to and including v5. After this, v6 was uploaded with no comment. Then, all files for the mission were deleted and cleanup was run. Then, a new v6 was uploaded. At this point, all previous comments are in order and marked "associated version was deleted", _except_ the comment for v5. The v5 comment is apparently associated with the new v6 file (i.e. not marked "associated version was deleted"), and appears after the v6 file in the list - even though it was posted before any v6 file was uploaded.

**Comment by SamLex** [comment]
Weird! Thanks for the detailed report, will see if I can work out why this happened.

**Comment by SamLex** [comment]
Okay, worked out the issue and know the fix. Won't go into the technical details but TLDR is the versions have an internal identifier. This internal id is unique at a single point in time, but not (currently) over time. So, in some situations a new version can get the same id as an old, deleted version. And thus commented get associated with it since it's got the same id.

Fix is to make the ids unique over time as well. Luckily relatively easy thing todo.

**Comment by SamLex** [comment]
Fixed and deployed. Unfortunately doesn't work retroactively but this issue shouldn't reoccur
